api:
  credentials:
    api-key: 07yFPJlYHoqXWlpvGcoTwOMLrrLUIyWKHyLz4C9pBJ348RVbQy5Xf0ZEhOXJDwIi
    secret: TZMK5IgyGlxliTsMnt1wds3eNBC8FtugGWfj6BylF1QAdVC9Ltz7I3pWMlTAO1AR
  trades:
    base-url: https://testnet.binance.vision
    websocket-base-url: wss://stream.testnet.binance.vision:9443
  base-url: https://api.binance.com
  websocket-base-url: wss://stream.binance.com:9443

klines:
  - BTCUSDT:
      period: 15m

signals:
  - ReverseMeanSignalBTC :
      symbol: BTCUSDT
      detector: ReverseMeanSignalDetector
      need_klines: true

traders:
  - ReverseMeanTraderBTC:
      symbol: BTCUSDT
      detector: ReverseMeanSignalDetector
      capital: 1000
      fees:
        quantity: 0.0001
        slots: 999
      trade-quantity: 0.001


