api:
  credentials:
    api-key: 07yFPJlYHoqXWlpvGcoTwOMLrrLUIyWKHyLz4C9pBJ348RVbQy5Xf0ZEhOXJDwIi
    secret: TZMK5IgyGlxliTsMnt1wds3eNBC8FtugGWfj6BylF1QAdVC9Ltz7I3pWMlTAO1AR
  trades:
    base-url: https://testnet.binance.vision
    websocket-base-url: wss://stream.testnet.binance.vision:9443
  base-url: https://api.binance.com
  websocket-base-url: wss://stream.binance.com:9443
price:
  symbols:
    - BTCUSDT
    - ETHUSDT
    - SOLUDST

signals:
  - ReverseMeanSignalBTC :
      symbol: BTCUSDT
      detector: ReverseMeanSignalDetector
  - ReverseMeanSignalETH:
      symbol: ETHUSDT
      detector: ReverseMeanSignalDetector
  - ReverseMeanSignalSOL:
      symbol: SOLUSDT
      detector: ReverseMeanSignalDetector


